// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSS_Time_Tracker.Data;

#nullable disable

namespace PSS_Time_Tracker.Migrations
{
    [DbContext(typeof(timeSheetRecorderContext))]
    [Migration("20260804100731_two")]
    partial class two
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSS_Time_Tracker.ApprovalUserCountResult", b =>
                {
                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.ToTable("ApprovalUserCountResults");
                });

            modelBuilder.Entity("PSS_Time_Tracker.EmployeeSummaryResult", b =>
                {
                    b.Property<string>("AzureAdUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LatestEntry")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimesheetCount")
                        .HasColumnType("int");

                    b.ToTable("EmployeeSummaryResults");
                });

            modelBuilder.Entity("PSS_Time_Tracker.Models.HostCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HostCompanies");
                });

            modelBuilder.Entity("PSS_Time_Tracker.Models.UserAccount", b =>
                {
                    b.Property<string>("AzureAdUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AzureAdUserId");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalStatus");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmployeeName");

                    b.Property<string>("EmployeeSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmployeeSurname");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JobTitle");

                    b.Property<string>("SupervisorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SupervisorEmail");

                    b.Property<string>("SupervisorFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SupervisorFullName");

                    b.HasKey("AzureAdUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PSS_Time_Tracker.SpResult", b =>
                {
                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.ToTable("SpResults");
                });

            modelBuilder.Entity("PSS_Time_Tracker.TimesheetCountResult", b =>
                {
                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.ToTable("TimesheetCountResults");
                });

            modelBuilder.Entity("TimeSheetRecorder.Models.TimeTrackerModel", b =>
                {
                    b.Property<int>("TimeTrackerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeTrackerId"));

                    b.Property<string>("AzureAdUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DailyTask")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfEntry")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HostCompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublicHoliday")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupervisorFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeSheetMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalHrsWorked")
                        .HasColumnType("float");

                    b.Property<string>("UserAccountAzureAdUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TimeTrackerId");

                    b.HasIndex("UserAccountAzureAdUserId");

                    b.ToTable("TimeTracker");
                });

            modelBuilder.Entity("TimeSheetRecorder.Models.TimeTrackerModel", b =>
                {
                    b.HasOne("PSS_Time_Tracker.Models.UserAccount", null)
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserAccountAzureAdUserId");
                });

            modelBuilder.Entity("PSS_Time_Tracker.Models.UserAccount", b =>
                {
                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
