// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSS_Time_Tracker.Data;

#nullable disable

namespace PSS_Time_Tracker.Migrations
{
    [DbContext(typeof(timeSheetRecorderContext))]
    [Migration("20260908123602_RemoveHostCompanyAddWorkLocation")]
    partial class RemoveHostCompanyAddWorkLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSS_Time_Tracker.ApprovalUserCountResult", b =>
                {
                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.ToTable("ApprovalUserCountResults");
                });

            modelBuilder.Entity("PSS_Time_Tracker.EmployeeSummaryResult", b =>
                {
                    b.Property<string>("AzureAdUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LatestEntry")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimesheetCount")
                        .HasColumnType("int");

                    b.ToTable("EmployeeSummaryResults");
                });

            modelBuilder.Entity("PSS_Time_Tracker.Models.ClockEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureAdUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("RawPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClockEvents");
                });

            modelBuilder.Entity("PSS_Time_Tracker.Models.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AccruedDays")
                        .HasColumnType("float");

                    b.Property<string>("AzureAdUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<double>("UsedDays")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveBalances");
                });

            modelBuilder.Entity("PSS_Time_Tracker.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressDuringLeave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AzureAdUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapturedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CapturedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmployeeSignatureDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HrDecision")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HrDecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HrRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HrSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HrUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("ManagerApprovedPaidLeave")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ManagerDecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ManagerRecommendation")
                        .HasColumnType("int");

                    b.Property<string>("ManagerRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherLeaveDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalDays")
                        .HasColumnType("float");

                    b.Property<string>("VerifiedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("PSS_Time_Tracker.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultAnnualDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");
                });

            modelBuilder.Entity("PSS_Time_Tracker.Models.UserAccount", b =>
                {
                    b.Property<string>("AzureAdUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AzureAdUserId");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalStatus");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmployeeName");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmployeeNumber");

                    b.Property<string>("EmployeeSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmployeeSurname");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IdNumber");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit")
                        .HasColumnName("IsManager");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JobTitle");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("SupervisorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SupervisorEmail");

                    b.Property<string>("SupervisorFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SupervisorFullName");

                    b.HasKey("AzureAdUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PSS_Time_Tracker.SpResult", b =>
                {
                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.ToTable("SpResults");
                });

            modelBuilder.Entity("PSS_Time_Tracker.TimesheetCountResult", b =>
                {
                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.ToTable("TimesheetCountResults");
                });

            modelBuilder.Entity("TimeSheetRecorder.Models.TimeTrackerModel", b =>
                {
                    b.Property<int>("TimeTrackerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeTrackerId"));

                    b.Property<string>("AzureAdUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DailyTask")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfEntry")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlagReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFlaggedForReview")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublicHoliday")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupervisorFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeSheetMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalHrsWorked")
                        .HasColumnType("float");

                    b.Property<string>("UserAccountAzureAdUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TimeTrackerId");

                    b.HasIndex("UserAccountAzureAdUserId");

                    b.ToTable("TimeTracker");
                });

            modelBuilder.Entity("PSS_Time_Tracker.Models.LeaveBalance", b =>
                {
                    b.HasOne("PSS_Time_Tracker.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("PSS_Time_Tracker.Models.LeaveRequest", b =>
                {
                    b.HasOne("PSS_Time_Tracker.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("TimeSheetRecorder.Models.TimeTrackerModel", b =>
                {
                    b.HasOne("PSS_Time_Tracker.Models.UserAccount", null)
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserAccountAzureAdUserId");
                });

            modelBuilder.Entity("PSS_Time_Tracker.Models.UserAccount", b =>
                {
                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
